# Generated by Django 4.2.4 on 2023-08-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_2', '0003_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1998, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='add_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
